"""Criação completa do domínio: categorias, instrumentos, maletas, movimentações e ocorrências

Revision ID: 51e493064c47
Revises: 8ed949aa0aee
Create Date: 2025-12-08 12:23:20.789405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e493064c47'
down_revision = '8ed949aa0aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maleta_instrumento',
    sa.Column('maleta_id', sa.Integer(), nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=False),
    sa.Column('quantidade_ideal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ),
    sa.ForeignKeyConstraint(['maleta_id'], ['maletas.id'], ),
    sa.PrimaryKeyConstraint('maleta_id', 'instrumento_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maleta_instrumento')
    # ### end Alembic commands ###
