"""Código interno automático para instrumentos

Revision ID: 89ecaf326545
Revises: 51e493064c47
Create Date: 2025-12-08 15:12:26.165645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89ecaf326545'
down_revision = '51e493064c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrumentos', schema=None) as batch_op:
        batch_op.alter_column('codigo_interno',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('codigo_interno'))
        batch_op.create_index(batch_op.f('ix_instrumentos_codigo_interno'), ['codigo_interno'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrumentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrumentos_codigo_interno'))
        batch_op.create_index(batch_op.f('codigo_interno'), ['codigo_interno'], unique=True)
        batch_op.alter_column('codigo_interno',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
