"""Modelos do domínio: categorias, instrumentos, maletas, movimentações, ocorrências

Revision ID: 8ed949aa0aee
Revises: b3e566a5be67
Create Date: 2025-12-08 12:17:10.102985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed949aa0aee'
down_revision = 'b3e566a5be67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('maletas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('codigo_maleta', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_maleta')
    )
    op.create_table('instrumentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=True),
    sa.Column('estoque_maximo', sa.Integer(), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_interno')
    )
    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=False),
    sa.Column('maleta_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ),
    sa.ForeignKeyConstraint(['maleta_id'], ['maletas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=True),
    sa.Column('maleta_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ),
    sa.ForeignKeyConstraint(['maleta_id'], ['maletas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocorrencias')
    op.drop_table('movimentacoes')
    op.drop_table('instrumentos')
    op.drop_table('maletas')
    op.drop_table('categorias')
    # ### end Alembic commands ###
