"""Atualização prática

Revision ID: b67c83901f84
Revises: 89ecaf326545
Create Date: 2025-12-08 16:06:29.030347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b67c83901f84'
down_revision = '89ecaf326545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrumentos', schema=None) as batch_op:
        batch_op.alter_column('codigo_interno',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('qr_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('ocorrencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencias', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('instrumentos', schema=None) as batch_op:
        batch_op.alter_column('qr_code',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('codigo_interno',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
