"""Adiciona tabela movimentacoes e campos necessários

Revision ID: ee9da7bf031d
Revises: b67c83901f84
Create Date: 2025-12-19 17:17:17.807297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee9da7bf031d'
down_revision = 'b67c83901f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('responsavel', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('origem_destino', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('movimentacoes_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('data_hora')
        batch_op.drop_column('localizacao')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('localizacao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
        batch_op.add_column(sa.Column('data_hora', mysql.DATETIME(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('movimentacoes_ibfk_3'), 'users', ['usuario_id'], ['id'])
        batch_op.drop_column('notas')
        batch_op.drop_column('origem_destino')
        batch_op.drop_column('responsavel')
        batch_op.drop_column('data')

    # ### end Alembic commands ###
